{% set name = "scons" %}
{% set version = "3.1.1" %}
{% set sha256 = "fd44f8f2a4562e7e5bc8c63c82b01e469e8115805a3e9c2923ee54cdcd6678b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # be careful of using "noarch: python": we have had trouble in the past in a single platform (#2)
  # which would not be caught by the noarch package
  number: 0
  # scons has a custom setup.py script, --standard-lib is a custom option
  script: python setup.py install --standard-lib

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - SCons
    - SCons.Node
    - SCons.Platform
    - SCons.Scanner
    - SCons.Script
    - SCons.Tool
    - SCons.Tool.MSCommon
    - SCons.Tool.docbook
    - SCons.Tool.packaging
    - SCons.Variables
    - SCons.compat
  commands:
    - scons --help

about:
  home: http://www.scons.org/
  license: MIT
  license_family: MIT
  summary: 'Open Source next-generation build tool.'
  description: |
    SCons is an Open Source software construction tool that is, a
    next-generation build tool. Think of SCons as an improved, cross-platform
    substitute for the classic Make utility with integrated functionality
    similar to autoconf/automake and compiler caches such as ccache. In short,
    SCons is an easier, more reliable and faster way to build software.
  doc_url: http://scons.org/documentation.html
  dev_url: https://bitbucket.org/scons/scons

extra:
  recipe-maintainers:
    - stuertz
    - nicoddemus
