{% set name = "scons" %}
{% set version = "4.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99c0e94a42a2c1182fa6859b0be697953db07ba936ecc9817ae0d218ced20b15

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - scons = SCons.Script.Main:main
    - sconsign = SCons.Utilities.sconsign:main
    - scons-configure-cache = SCons.Utilities.ConfigureCache:main
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0
  run:
    - python

test:
  requires:
    - pip
  imports:
    - SCons
    - SCons.Node
    - SCons.Platform
    - SCons.Scanner
    - SCons.Script
    - SCons.Tool
    - SCons.Tool.MSCommon
    - SCons.Tool.docbook
    - SCons.Tool.packaging
    - SCons.Variables
    - SCons.compat
  commands:
    - scons --help
    - sconsign --help
    - scons-configure-cache --help
    - pip check

about:
  home: https://www.scons.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open Source next-generation build tool.
  description: |
    SCons is an Open Source software construction tool that is, a
    next-generation build tool. Think of SCons as an improved, cross-platform
    substitute for the classic Make utility with integrated functionality
    similar to autoconf/automake and compiler caches such as ccache. In short,
    SCons is an easier, more reliable and faster way to build software.
  doc_url: https://scons.org/documentation.html
  dev_url: https://github.com/SCons/scons

extra:
  recipe-maintainers:
    - stuertz
    - nicoddemus
