travis:
  secure:
    BINSTAR_TOKEN: Ieh6tNPdeRRKkQe+MrpV83QiATpmhzS/iQd06RAttc8Yft2qcdK4jKnJ8Q477fwZaX+kI/jtlt0cHs6owwt2YHFielhgIJOUzSYRC4EP5qYVgSwcnhCdKuK/mKGJKxxk9H01y83QygNCLkfzuNKpcDHYrcjGM8K/T2fmk0htwxsr3WaNnjqOnK9LnNQBsWeTMjpCpzQRzBcBZ6tNjSAX9yyT0BbmzpZZx5DY8bNgMVsC0l+ItKzHREwfVb0QIwGhkgo5Zo3g+H1ClLdR6+LVxqge9n545IYVngfWNyCbPQ8gXaHjEBiAVbU1yBCoklBa9hjWxb5ygpUiBcUfo8e1xke04cd6otfrn6VY3RrOGn6FWvqGond9ydJGlCBlqWVuGCa7aJjsKOxk5lGP31Qi4JY7zUAdNj+/RmSHgBW+ey6HYjBJiOScoTxlIZwkCGV40T5SnvpwG0F3SynNmsp7rT2k4BOUT9i7NtXzPn+nLiPw+bGsVh9+2skZ3C0J55U0t5GcHCqmGXnL8aAAi+/BN7wQn+L8FagECGmmsSW807TlPGtxitNdz+vkAauQXWYiSjZHQGbV0i7dQ1tTFUyIIX2p5B1rJYH/Ch3/TmK0Y9QH3ldQG9e0XwxwoOt13QnSSJ4WT8w2nVnP5tZTBZoq31MEl92vptdRcruhQSzNwgg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
