travis:
  secure:
    BINSTAR_TOKEN: ZMch3GEnaOaaPiV9+YOVCsiR8m7/SpGC6Z5+6JOuXvkxXKhQwHrFOS69AzYgJgkGNZoWnmh0i7n2t3464GaJ1hwiIoVX9DSH2XMwz1wN1tHxJLEsQFln8GbHTE+AdmbJpa/U2lz8IJcfA5wrjBo8wosuAkT9W+C6fb4ggzSRkCCqcBfP/8vYkOaThSHuq/XHxKoWuVe9kjrHCB7+2wLzEYWupSft7MnkiFUw/zpHMQjJyokmBXqP1IJWfYSgw3zdGSxJ9vfQXHQJbe7LNgrEwtW+ux4KsGTF4MjVmcu35VPiqzTtmUfDw8eGP+X3Bb81S4dPDeOWfGSpCCM9CeRrzsDrZUs/Al/qmfN2EQf0nhrz4oM6Qf0dZLxAVt0c9ZtMblNXhrgXBhgNMxkCDBQ77DgZcSdA4FYjVnuP7EyhS8Hqp36RAnCxaYAJx3XffeXjrq0b1ohowwm3YxYgwKPmBveu1D6du+4fL6tvmqulo2S+V5MQDVMx+bcJg0BH4w5+ZANfuE0lyxxnHChqp0Lo5iqNhZbweYhaAuTpZ/tstHDt3TmzPcFKyOyGh4Q42KV2IyChSdPMVksVuLhghDF6QI3tDKGzcpiXCKOitQ3mpGQwfF2rn2JV9UPOGWrMW/2vAg3OL1fa4CKdxvi6ZVPCZSpMa5oMLtKWshuPk6E6vHM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
